CREATE TABLE IF NOT EXISTS {}.app_links (
  id INT(12) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT(12) NOT NULL,
  name VARCHAR(255) NOT NULL,
  icon TEXT NOT NULL,
  url TEXT NOT NULL,
  INDEX aname (name),
  CONSTRAINT fk_userid FOREIGN KEY (user_id)
  REFERENCES users(id)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);